# Generated by Django 3.1.8 on 2021-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_logicalcluster_partial_reload'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalcluster',
            name='service_mesh_routing',
            field=models.BooleanField(default=False),
        ),
    ]
