# Generated by Django 3.1.14 on 2022-06-07 09:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20220209_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc',
            name='symbol',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_\\-]+$'), 'Allowed characters: letters, numbers, dashes and underscores .', 'invalid')]),
        ),
    ]
