# Generated by Django 3.1.14 on 2022-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20220607_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalcluster',
            name='labels_list',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
