# Generated by Django 3.1.14 on 2023-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_logicalcluster_labels_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True)),
                ('mapping', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=7)),
                ('clusters', models.ManyToManyField(to='cluster.LogicalCluster')),
            ],
        ),
    ]
