# Generated by Django 3.1.14 on 2023-03-28 14:41
import json

from django.db import migrations, models


def migrate_mappings(apps, schema_editor):
    DomainMapping = apps.get_model('cluster', 'domainmapping')
    for row in DomainMapping.objects.all():
        if row.mapping:
            row.mappings_list = json.dumps([row.mapping])
            row.save(update_fields=['mappings_list'])


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_domainmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainmapping',
            name='mappings_list',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.RunPython(migrate_mappings, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='domainmapping',
            name='mapping',
        ),
    ]
