# Generated by Django 3.1.14 on 2023-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_domainmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmapping',
            name='mapping',
        ),
        migrations.AddField(
            model_name='domainmapping',
            name='mappings_list',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
