# Generated by Django 3.1.14 on 2022-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_domainmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmapping',
            name='domain',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
