# Generated by Django 5.2.5 on 2025-08-26 09:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from vaas.utils.migrations import create_model_if_not_exists_factory


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_auto_20230328_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvcltemplate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vcl template', 'verbose_name_plural': 'historical vcl templates'},
        ),
        migrations.AlterModelOptions(
            name='historicalvcltemplateblock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vcl template block', 'verbose_name_plural': 'historical vcl template blocks'},
        ),
        migrations.AlterField(
            model_name='historicalvcltemplate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvcltemplateblock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicaldomainmapping',
                app_label='cluster',
                model_name='HistoricalDomainMapping'
            )
        ),
    ]
