# Generated by Django 5.2.5 on 2025-08-26 09:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_auto_20230328_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvcltemplate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vcl template', 'verbose_name_plural': 'historical vcl templates'},
        ),
        migrations.AlterModelOptions(
            name='historicalvcltemplateblock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vcl template block', 'verbose_name_plural': 'historical vcl template blocks'},
        ),
        migrations.AlterField(
            model_name='historicalvcltemplate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvcltemplateblock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='HistoricalDomainMapping',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=128)),
                ('mappings_list', models.CharField(default='[]', max_length=500)),
                ('type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical domain mapping',
                'verbose_name_plural': 'historical domain mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
