# Generated by Django 5.2.5 on 2025-09-23 09:43

import django.utils.timezone
import re
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from vaas.utils.migrations import create_model_if_not_exists_factory


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_alter_historicalvcltemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicaldc',
                app_label='cluster',
                model_name='HistoricalDc'
            )
        ),
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicallogicalcluster',
                app_label='cluster',
                model_name='HistoricalLogicalCluster'
            )
        ),
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicalvarnishserver',
                app_label='cluster',
                model_name='HistoricalVarnishServer'
            )
        ),
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicalvclvariable',
                app_label='cluster',
                model_name='HistoricalVclVariable'
            )
        ),
    ]
