# Generated by Django 5.2.5 on 2025-09-24 08:28

from django.db import migrations, models
from vaas.utils.migrations import create_model_if_not_exists_factory

class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_historicaldc_historicallogicalcluster_and_more'),
    ]
    operations = [
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='cluster_historicaldomainmapping_clusters',
                app_label='cluster',
                model_name='HistoricalDomainMapping_clusters'
            )
        ),
    ]
