# Generated by Django 5.2.5 on 2025-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_historicaldomainmapping_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmapping',
            name='type',
            field=models.CharField(choices=[('static', 'Static'), ('static_regex', 'Static Regex'), ('dynamic', 'Dynamic')], default='static', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicaldomainmapping',
            name='type',
            field=models.CharField(choices=[('static', 'Static'), ('static_regex', 'Static Regex'), ('dynamic', 'Dynamic')], default='static', max_length=12),
        ),
    ]
