services:
  celery-worker:
    entrypoint: [ '/entrypoint-celery-worker.sh' ]
    env_file: ./envs/dev.env
    volumes:
      - ./vaas:/home/app/vaas
      - ./plugins:/home/app/plugins
    networks:
      - vaas
      - default
  celery-cron-worker:
    entrypoint: [ '/entrypoint-celery-cron-worker.sh' ]
    env_file: ./envs/dev.env
    volumes:
      - ./vaas:/home/app/vaas
      - ./plugins:/home/app/plugins
    networks:
      - vaas
      - default
  celery-routes-test:
    entrypoint: [ '/entrypoint-celery-routes-test.sh' ]
    env_file: ./envs/dev.env
    volumes:
      - ./vaas:/home/app/vaas
      - ./plugins:/home/app/plugins
    networks:
      - vaas
      - default
  uwsgi:
    entrypoint: ['/wait-for-it.sh', 'mysql:3306', '-t', '30', '--', '/entrypoint-uwsgi-dev.sh' ]
    env_file: ./envs/dev.env
    volumes:
      - ./vaas:/home/app/vaas
      - ./plugins:/home/app/plugins
    networks:
      - vaas
      - default
  celery-scheduler:
    entrypoint: ['/wait-for-it.sh', 'uwsgi:3030', '-t', '60', '--', '/entrypoint-celery-scheduler.sh' ]
    env_file: ./envs/dev.env
    volumes:
      - ./vaas:/home/app/vaas
      - ./plugins:/home/app/plugins
    networks:
      - vaas
      - default

  # Varnishes & nginx
  nginx-0:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.10
  nginx-1:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.11
  nginx-2:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.12
  nginx-3:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.13
  nginx-4:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.14
  nginx-5:
    build: ./docker/nginx
    image: vaas-nginx
    expose:
      - "80"
    networks:
      vaas:
        ipv4_address: 192.168.199.15
  varnish-4.1:
    build: ./docker/varnish-4.1
    image: allegro/vaas-varnish-4.1
    expose:
      - "6082"
      - "6081"
    networks:
      vaas:
        ipv4_address: 192.168.199.4
  varnish-6.0.2:
    build: ./docker/varnish-6.0.2
    image: allegro/vaas-varnish-6.0.2
    expose:
      - "6082"
      - "6081"
    networks:
      vaas:
        ipv4_address: 192.168.199.6
  varnish-7.0:
    build: ./docker/varnish-7.0
    image: allegro/vaas-varnish-7.0
    expose:
      - "6082"
      - "6081"
    networks:
      vaas:
        ipv4_address: 192.168.199.7
networks:
  vaas:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.199.0/24
          gateway: 192.168.199.1
