version: "3.9"
services:
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_DATABASE: vaas
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppassword", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 3s
  uwsgi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    depends_on:
      - redis
      - rabbitmq
      - mysql
  rabbitmq:
    image: rabbitmq:3.11-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      - RABBITMQ_DEFAULT_VHOST=myvhost
    ports:
      - 5672:5672
      - 15672:15672
  celery-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - mysql
  celery-cron-worker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - mysql
  celery-routes-test:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq
      - mysql
  # celery-scheduler:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis
  #     - mysql
