site_name: VaaS
repo_url: https://github.com/allegro/vaas
nav:
- 'About': 'index.md'
- 'Quick Start':
  - 'VaaS in Docker Compose': 'quick-start/docker_compose.md'
  - 'VaaS in Production': 'quick-start/production.md'
- 'Documentation':
  - 'VaaS request flow': 'documentation/flow.md'
  - 'VaaS GUI': 'documentation/gui.md' 
  - 'VaaS API': 'documentation/api.md'
  - 'VCL templates': 'documentation/vcl.md'
  - 'VaaS in multiple DC scenario': 'documentation/dc.md'
  - 'Protocol Support': 'documentation/protocol.md'
  - 'Authentication with LDAP': 'documentation/ldap.md'
  - 'VaaS cron jobs': 'documentation/cron.md'
  - 'Canary deployments support': 'documentation/canary.md'
