# Generated by Django 3.1.5 on 2021-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='cluster',
            field=models.ManyToManyField(related_name='directory', to='cluster.LogicalCluster'),
        ),
    ]
