# Generated by Django 3.1.13 on 2021-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_director_reachable_via_service_mesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='reachable_via_service_mesh',
            field=models.BooleanField(default=True, help_text='<i>Pass traffic to backends via service mesh if varnish cluster supports it</i>'),
        ),
    ]
