# Generated by Django 5.2.5 on 2025-09-24 08:28

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_historicaldomainmapping_clusters'),
        ('manager', '0010_alter_backend_between_bytes_timeout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDirector_cluster',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('director', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manager.director')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.historicaldirector')),
                ('logicalcluster', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cluster.logicalcluster')),
            ],
            options={
                'verbose_name': 'HistoricalDirector_cluster',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
