# Generated by Django 3.1.5 on 2021-03-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalcluster',
            name='partial_reload',
            field=models.BooleanField(default=False),
        ),
    ]
