# Generated by Django 3.1.14 on 2022-11-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_route_clusters_in_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=512)),
                ('destination', models.CharField(max_length=512)),
                ('action', models.CharField(choices=[('301', 'Move Pernamentlly'), ('302', 'Found'), ('307', 'Temporary Redirect')], default='301', max_length=3)),
                ('priority', models.PositiveIntegerField()),
                ('preserve_query_params', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewritePositiveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('expected_location', models.CharField(max_length=512)),
                ('rewrite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewritre_positive_urls', related_query_name='rewritre_positive_url', to='router.rewrite')),
            ],
        ),
    ]
