# Generated by Django 3.1.14 on 2022-12-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_redirect_redirectassertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='rewrite_groups',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
