# Generated by Django 5.2.5 on 2025-09-23 09:43

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models
from vaas.utils.migrations import create_model_if_not_exists_factory

class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_historicaldc_historicallogicalcluster_and_more'),
        ('manager', '0010_alter_backend_between_bytes_timeout_and_more'),
        ('router', '0003_redirect_redirectassertion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='router_historicalredirect',
                app_label='router',
                model_name='HistoricalRedirect'
            )
        ),
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='router_historicalroute',
                app_label='router',
                model_name='HistoricalRoute'
            )
        ),
    ]
