# Generated by Django 3.1.14 on 2022-11-25 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_rewrite_rewritepositiveurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewritepositiveurl',
            name='rewrite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_positive_urls', related_query_name='rewrite_positive_url', to='router.rewrite'),
        ),
    ]