# Generated by Django 5.2.5 on 2025-09-24 08:28

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_historicaldomainmapping_clusters'),
        ('router', '0004_historicalredirect_historicalroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoute_clusters',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='router.historicalroute')),
                ('logicalcluster', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cluster.logicalcluster')),
                ('route', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='router.route')),
            ],
            options={
                'verbose_name': 'HistoricalRoute_clusters',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
