# Generated by Django 5.2.5 on 2025-09-24 08:28

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models
from vaas.utils.migrations import create_model_if_not_exists_factory

class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_historicaldomainmapping_clusters'),
        ('router', '0004_historicalredirect_historicalroute'),
    ]

    operations = [
        migrations.RunPython(
            create_model_if_not_exists_factory(
                table_name='router_historicalroute_clusters',
                app_label='router',
                model_name='HistoricalRoute_clusters'
            )
        ),
    ]
