# Generated by Django 3.1.14 on 2022-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_auto_20221125_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewrite',
            name='domain',
            field=models.CharField(default='', max_length=512),
        ),
    ]
