# Generated by Django 3.1.14 on 2023-01-04 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_auto_20221230_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
