# Generated by Django 3.1.5 on 2021-01-21 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=512)),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                                     django.core.validators.MaxValueValidator(500)])),
                ('action', models.CharField(max_length=20)),
                ('clusters', models.ManyToManyField(to='cluster.LogicalCluster')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.director')),
            ],
        ),
        migrations.CreateModel(
            name='PositiveUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_urls',
                                            related_query_name='positive_url', to='router.route')),
            ],
        ),
    ]
