# Generated by Django 3.1.5 on 2021-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('address', 'port')},
            },
        ),
    ]
