# Generated by Django 3.1.6 on 2021-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_logicalcluster_partial_reload'),
        ('manager', '0002_auto_20210225_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='cluster',
            field=models.ManyToManyField(to='cluster.LogicalCluster'),
        ),
    ]
