# Generated by Django 3.1.8 on 2021-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210414_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='virtual',
            field=models.BooleanField(default=False,
                                      help_text='<i>Virtual director will not be available in routes</i>'),
        ),
    ]
