# Generated by Django 3.1.8 on 2021-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_director_envoy_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='envoy_service_name',
            field=models.CharField(max_length=128),
        ),
    ]
