# Generated by Django 3.1.13 on 2021-10-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_director_service_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='reachable_via_service_mesh',
            field=models.BooleanField(blank=False, default=True),
        ),
    ]
